// Code generated by gen.go; DO NOT EDIT.

package hardforks

import (
	"encoding/json"
	"fmt"
	"math"
)

var Forks = []Fork{Regolith, Delta, Ecotone, Fjord, Granite, Holocene, Isthmus, Interop, Jovian}

var forkNames = []string{"regolith", "delta", "ecotone", "fjord", "granite", "holocene", "isthmus", "interop", "jovian"}

func (f Fork) String() string {
	return forkNames[f]
}

type Schedule struct {
	regolithTime *uint64
	deltaTime    *uint64
	ecotoneTime  *uint64
	fjordTime    *uint64
	graniteTime  *uint64
	holoceneTime *uint64
	isthmusTime  *uint64
	interopTime  *uint64
	jovianTime   *uint64
}

type jsonSchedule struct {
	RegolithTime *uint64 `json:"regolith_time,omitempty"`
	DeltaTime    *uint64 `json:"delta_time,omitempty"`
	EcotoneTime  *uint64 `json:"ecotone_time,omitempty"`
	FjordTime    *uint64 `json:"fjord_time,omitempty"`
	GraniteTime  *uint64 `json:"granite_time,omitempty"`
	HoloceneTime *uint64 `json:"holocene_time,omitempty"`
	IsthmusTime  *uint64 `json:"isthmus_time,omitempty"`
	InteropTime  *uint64 `json:"interop_time,omitempty"`
	JovianTime   *uint64 `json:"jovian_time,omitempty"`
}

func (s Schedule) MarshalJSON() ([]byte, error) {
	return json.Marshal(jsonSchedule{
		RegolithTime: s.regolithTime,
		DeltaTime:    s.deltaTime,
		EcotoneTime:  s.ecotoneTime,
		FjordTime:    s.fjordTime,
		GraniteTime:  s.graniteTime,
		HoloceneTime: s.holoceneTime,
		IsthmusTime:  s.isthmusTime,
		InteropTime:  s.interopTime,
		JovianTime:   s.jovianTime,
	})
}

func (s *Schedule) UnmarshalJSON(data []byte) error {
	var js jsonSchedule
	if err := json.Unmarshal(data, &js); err != nil {
		return err
	}

	*s = Schedule{
		regolithTime: js.RegolithTime,
		deltaTime:    js.DeltaTime,
		ecotoneTime:  js.EcotoneTime,
		fjordTime:    js.FjordTime,
		graniteTime:  js.GraniteTime,
		holoceneTime: js.HoloceneTime,
		isthmusTime:  js.IsthmusTime,
		interopTime:  js.InteropTime,
		jovianTime:   js.JovianTime,
	}
	return nil
}

func NewScheduleWithGenesisFork(fork Fork) *Schedule {
	sched := new(Schedule)
	if err := sched.ActivateAtGenesis(fork); err != nil {
		panic(fmt.Errorf("failed to activate genesis fork - should not happen: %w", err))
	}
	return sched
}

func (s *Schedule) ActivateAtGenesis(fork Fork) error {
	for i := 0; i <= int(fork); i++ {
		s.setFork(Fork(i), new(uint64))
	}
	return s.check()
}

func (s *Schedule) Activate(fork Fork, time *uint64) error {
	s.setFork(fork, time)
	return s.check()
}

func (s *Schedule) ForceSetForkDoNotUseInProdOrYouWillBeFired(fork Fork, time *uint64) {
	s.setFork(fork, time)
}

func (s *Schedule) IsActive(fork Fork, timestamp uint64) bool {
	return s.getFork(fork) != nil && timestamp >= *s.getFork(fork)
}

func (s *Schedule) IsRegolith(timestamp uint64) bool {
	return s.IsActive(Regolith, timestamp)
}

func (s *Schedule) IsRegolithActivationBlock(blockTime uint64, timestamp uint64) bool {
	return s.IsRegolith(timestamp) && timestamp >= blockTime && !s.IsRegolith(timestamp-blockTime)
}

func (s *Schedule) RegolithTimeOffset(genesisTime uint64) *uint64 {
	if s.regolithTime == nil {
		return nil
	}
	if *s.regolithTime < genesisTime {
		return new(uint64)
	}
	out := *s.regolithTime - genesisTime
	return &out
}

func (s *Schedule) IsDelta(timestamp uint64) bool {
	return s.IsActive(Delta, timestamp)
}

func (s *Schedule) IsDeltaActivationBlock(blockTime uint64, timestamp uint64) bool {
	return s.IsDelta(timestamp) && timestamp >= blockTime && !s.IsDelta(timestamp-blockTime)
}

func (s *Schedule) DeltaTimeOffset(genesisTime uint64) *uint64 {
	if s.deltaTime == nil {
		return nil
	}
	if *s.deltaTime < genesisTime {
		return new(uint64)
	}
	out := *s.deltaTime - genesisTime
	return &out
}

func (s *Schedule) IsEcotone(timestamp uint64) bool {
	return s.IsActive(Ecotone, timestamp)
}

func (s *Schedule) IsEcotoneActivationBlock(blockTime uint64, timestamp uint64) bool {
	return s.IsEcotone(timestamp) && timestamp >= blockTime && !s.IsEcotone(timestamp-blockTime)
}

func (s *Schedule) EcotoneTimeOffset(genesisTime uint64) *uint64 {
	if s.ecotoneTime == nil {
		return nil
	}
	if *s.ecotoneTime < genesisTime {
		return new(uint64)
	}
	out := *s.ecotoneTime - genesisTime
	return &out
}

func (s *Schedule) IsFjord(timestamp uint64) bool {
	return s.IsActive(Fjord, timestamp)
}

func (s *Schedule) IsFjordActivationBlock(blockTime uint64, timestamp uint64) bool {
	return s.IsFjord(timestamp) && timestamp >= blockTime && !s.IsFjord(timestamp-blockTime)
}

func (s *Schedule) FjordTimeOffset(genesisTime uint64) *uint64 {
	if s.fjordTime == nil {
		return nil
	}
	if *s.fjordTime < genesisTime {
		return new(uint64)
	}
	out := *s.fjordTime - genesisTime
	return &out
}

func (s *Schedule) IsGranite(timestamp uint64) bool {
	return s.IsActive(Granite, timestamp)
}

func (s *Schedule) IsGraniteActivationBlock(blockTime uint64, timestamp uint64) bool {
	return s.IsGranite(timestamp) && timestamp >= blockTime && !s.IsGranite(timestamp-blockTime)
}

func (s *Schedule) GraniteTimeOffset(genesisTime uint64) *uint64 {
	if s.graniteTime == nil {
		return nil
	}
	if *s.graniteTime < genesisTime {
		return new(uint64)
	}
	out := *s.graniteTime - genesisTime
	return &out
}

func (s *Schedule) IsHolocene(timestamp uint64) bool {
	return s.IsActive(Holocene, timestamp)
}

func (s *Schedule) IsHoloceneActivationBlock(blockTime uint64, timestamp uint64) bool {
	return s.IsHolocene(timestamp) && timestamp >= blockTime && !s.IsHolocene(timestamp-blockTime)
}

func (s *Schedule) HoloceneTimeOffset(genesisTime uint64) *uint64 {
	if s.holoceneTime == nil {
		return nil
	}
	if *s.holoceneTime < genesisTime {
		return new(uint64)
	}
	out := *s.holoceneTime - genesisTime
	return &out
}

func (s *Schedule) IsIsthmus(timestamp uint64) bool {
	return s.IsActive(Isthmus, timestamp)
}

func (s *Schedule) IsIsthmusActivationBlock(blockTime uint64, timestamp uint64) bool {
	return s.IsIsthmus(timestamp) && timestamp >= blockTime && !s.IsIsthmus(timestamp-blockTime)
}

func (s *Schedule) IsthmusTimeOffset(genesisTime uint64) *uint64 {
	if s.isthmusTime == nil {
		return nil
	}
	if *s.isthmusTime < genesisTime {
		return new(uint64)
	}
	out := *s.isthmusTime - genesisTime
	return &out
}

func (s *Schedule) IsInterop(timestamp uint64) bool {
	return s.IsActive(Interop, timestamp)
}

func (s *Schedule) IsInteropActivationBlock(blockTime uint64, timestamp uint64) bool {
	return s.IsInterop(timestamp) && timestamp >= blockTime && !s.IsInterop(timestamp-blockTime)
}

func (s *Schedule) InteropTimeOffset(genesisTime uint64) *uint64 {
	if s.interopTime == nil {
		return nil
	}
	if *s.interopTime < genesisTime {
		return new(uint64)
	}
	out := *s.interopTime - genesisTime
	return &out
}

func (s *Schedule) IsJovian(timestamp uint64) bool {
	return s.IsActive(Jovian, timestamp)
}

func (s *Schedule) IsJovianActivationBlock(blockTime uint64, timestamp uint64) bool {
	return s.IsJovian(timestamp) && timestamp >= blockTime && !s.IsJovian(timestamp-blockTime)
}

func (s *Schedule) JovianTimeOffset(genesisTime uint64) *uint64 {
	if s.jovianTime == nil {
		return nil
	}
	if *s.jovianTime < genesisTime {
		return new(uint64)
	}
	out := *s.jovianTime - genesisTime
	return &out
}

func (s *Schedule) check() error {
	var lastForkTime uint64
	for i := 0; i < len(Forks)-1; i++ {
		forkTime := s.getFork(Forks[i])
		if forkTime == nil {
			maxU := uint64(math.MaxUint64)
			forkTime = &maxU
		}
		if lastForkTime > *forkTime {
			return fmt.Errorf("fork %s set to %d, but prior fork %s has higher offset %d", Forks[i], *forkTime, Forks[i-1], lastForkTime)
		}
		lastForkTime = *forkTime
	}
	return nil
}

func (s *Schedule) getFork(fork Fork) *uint64 {
	switch fork {
	case Regolith:
		return s.regolithTime
	case Delta:
		return s.deltaTime
	case Ecotone:
		return s.ecotoneTime
	case Fjord:
		return s.fjordTime
	case Granite:
		return s.graniteTime
	case Holocene:
		return s.holoceneTime
	case Isthmus:
		return s.isthmusTime
	case Interop:
		return s.interopTime
	case Jovian:
		return s.jovianTime
	default:
		panic("unknown fork")
	}
}

func (s *Schedule) setFork(fork Fork, time *uint64) {
	switch fork {
	case Regolith:
		s.regolithTime = time
	case Delta:
		s.deltaTime = time
	case Ecotone:
		s.ecotoneTime = time
	case Fjord:
		s.fjordTime = time
	case Granite:
		s.graniteTime = time
	case Holocene:
		s.holoceneTime = time
	case Isthmus:
		s.isthmusTime = time
	case Interop:
		s.interopTime = time
	case Jovian:
		s.jovianTime = time
	default:
		panic("unknown fork")
	}
}
